image: cypress/browsers:22.12.0

variables:
  GIT_DEPTH: "0"
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

stages:
  - build
  - test

before_script:
  - git config --system core.longpaths true
  - npm install wait-on

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

cypress-test:
  stage: test
  script:
    - npm ci
    - Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run dev"
    - npx wait-on http://localhost:5173 --timeout=5000
    - npx cypress run
  dependencies:
    - build